# .streamlit/secrets.toml

[firebase_credentials]
type = "service_account"
project_id = "processador-bom-solidworks"
private_key_id = "988d4c46f18cb3178d3b81f61a6d36e3082fdb30"

# Importante: A chave privada precisa estar entre aspas triplas para funcionar corretamente
# com as quebras de linha.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCviHMS2y1HKGcq
Q6QhAAaQMyxDE8K2Dxl2bK01VatEuZN4vJS4KkCNLXHn80a8bXx0eevFWZez+voF
KDY7zPwpNRzA5fCpQXCoyJRAwiSdgCLhmpBcphWGw9CY5u85AtUeiKSC5rFWYzwZ
P2Cp1Kz3oNwuB+u2pDFPOYBK4uA+yAkJ0t6UJ3KRv0fXIh0YI0rEiY0lCL42EixQ
XZTlqe+GrBBR+yPsixz+jjZx/G6pt22iqYeVlcUz3jaf7WF232IaOquPxH6X1wsH
VSjJRj39QOHF8QUMXaMeGf+sen13YAh7eCdM1k+1kP3n4XhHjiotIY7K+zsSsVnl
pbxfwCIhAgMBAAECggEAAuU0SLZWy9qtwPO2rFiswwolC8IyrwAWwm5OeRe9qHeL
KC2sIlGIGQwL2fCYVRlVOTKdofa1WuGj6BvesSPTcPaQT9o7Gv+aVR5h26OYKQTp
DmGXSf/vUPa/5RXCEmWqkENeu04E1ND0N9JkzMhWRgtgNl4pFC0nJxBivll5q29o
OfwdWguyIuUP8JrDu8welg7jMs8DARZfqhbeFfh+m2JkqX7QFOhmXaO8AuHs869S
FKtLnqtoWEfqPMPJUjZ9sXD5rTO7wTrBPfnmwtNx8AAjqMKuc1uirXzgWDH9xx2c
aNt0ifvC1npS70p2zphumUjW2FWLqm+Dexc63OtDMQKBgQDm3BAfMQXuQUrFQjc4
kQknNLUea/FfpxTllqzhePfKbiNUd/5sIBZcCNHUt8Ny5OYEOIUGYssdfkI0qV1N
lMCXiuApJRlZDrSc8cuXQM+IPZZOwm3w04h7LzOcuFo17jDkj5kFbz0945a8CeMk
zHz0vBR6D5tJcmMbxCnsFMH+5QKBgQDCpfu9sQhe/ngZ/La2c7fEyuwNsx796dZ/
NxPi05L8J7C+uD8gicvWgEAilnpiZzXgxfBWGxp1k+t0qKTltDjdDDwrOcl4MaDH
bZl/XNcmmvD9Xl6PHv/GVcjS85KrNfgS/xX67HJGGbHuH/ieibF9Bxb/I/SqWTfD
yiqYmwHmjQKBgQCKeCJfYxsojhcX/CB9GFlCH9YnGh2b/u6EyvyE/Pa7f5ZHWvXK
yvA+Ybfh/BsKNgtVKsV3UBh+ZzW0uoVRPFDMVKshYrQye6SPomQ4I9KW6EHYmbwx
v99T67rsXJMXV/gRj6P74337OiA2R0Pr1Y95h7pMgEHnKuoRRHbUuJqnlQKBgQCu
P0B4s342675AJUa7ViPwe2eNbAgWbbqi739R0u0F5dIHKZD5Y+GiB/ViAStV4+cL
bKaVrnWlQ+HH8SCMsSUmXMmQOI7ulh7D6I08wrOnz5RkfJJRtQJrXmgE0B9APXPy
LYBTvE8gCeiKrvw1kDXfIvWnOVzREkUldFlle33cEQKBgGfG9oVrR7jCB06kd7sF
var8/OF905twMLoj3k7noYOsAvFIK6GRouqjc4X3N9XEg/o1ZLso26lmNiSxsIGt
s66QkjkSYzjjnIu4BBQmzYloRbyxcKLqpao5ZWh2k/R2OrjvkD5wH4LfTYRO9/cf
U+2HLWtQpn4V5vmNMWAHoUAz
-----END PRIVATE KEY-----"""

client_email = "firebase-adminsdk-fbsvc@processador-bom-solidworks.iam.gserviceaccount.com"
client_id = "106413746155312907665"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40processador-bom-solidworks.iam.gserviceaccount.com"

# !! ATENÇÃO !!
# Adicione manualmente o URL do seu Realtime Database aqui.
# Você o encontra na tela do "Realtime Database" no Firebase.
databaseURL = "COLE_O_URL_DO_SEU_BANCO_DE_DADOS_AQUI"
